### ISSUE TITLE
org.hibernate.dialect.Oracle12cDialect is not supported

### ISSUE THREAD

**Issue by bbucko** [Devskiller/hbm2ddl-maven-plugin#19]
Setting hibernate.dialect to org.hibernate.dialect.Oracle12cDialect in jpaProperties results in a following error:
`Unable to build DatabaseInformation: Table "ALL_SEQUENCES" not found; SQL statement:
[ERROR]  select sequence_name from all_sequences  union select synonym_name   from all_synonyms us, all_sequences asq  where asq.sequence_name = us.table_name    and asq.sequence_owner = us.table_owner [42102-196]`

**Comment by bbucko** [comment]
Maybe this line is to blame: https://github.com/Devskiller/jpa2ddl/blob/f5076e76293e4414bf94787637b02cc550f0fc71/jpa2ddl-core/src/main/java/com/devskiller/jpa2ddl/engines/EngineDecorator.java#L20

**Comment by jkubrynski** [comment]
Released in 0.9.12
