### ISSUE TITLE
removed column not generated in migration script

### ISSUE THREAD

**Issue by ghost** [Devskiller/hbm2ddl-maven-plugin#25]
Hi,

i tested the jpa2dll plugin with the action UPDATE as folllows:

1. genrate a Entity Person (name)
2. mvn clean package -> resulting a script with a new table called person and a column called name

3. added a new attribute age to person
4. mvn clean package -> resulting a script to modify the table person (add cloumn age...)

5. added a new attribute firstname to person
6. mvn clean package -> resulting a script to modify the table person (add cloumn age...)

7. removed the attribute age from person
8. mvn clean package -> missing a statement for removing column

It is a bug or it is a normal behaviour? The 

Many Thanks

**Comment by jkubrynski** [comment]
Sorry for the delay. It's normal behavior. Hibernate is not generating drop statements.
